################################
#   Dalet Ingest Settings
################################

# Change these to reflect your computer's settings

# Dalet XML Ingest folder for audiovault metadata
meta_ingest: 
# Dalet media (staging) ingest folder for audiovault media
media_ingest: 

################################
#   Audiovault Settings
################################

# Locations of files on audiovault machine - should be static, but confirm

# Location of AVAir Access database file
av_location: 
# Location of audiovault media (base directory)
av_media: 

# Date of last known Audiovault ingest to Dalet - probably leave alone,
# Better to query too much than miss something.
last_ingest: [2015, 12, 5]


# Do not change settings below
media_files: .\media\
access_db: avair.mdb
staging: staging_folder
copy_bat: files_to_copy.bat
